

import { Roboto } from 'next/font/google';
import "./globals.css";

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Facebook",
  description: "Generated by create next app",
  icons: {
    icon: './logo.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={roboto.className}>{children}</body>
      </html>
    </>
  );
}
